name: build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [Release]
        ui: [gui]
        scripting: [lua]
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: 'recursive'
    - name: Install Skia
      if: ${{ matrix.ui == 'gui' }}
      shell: bash
      run: |
        this_dir=$(cygpath "${{ github.workspace }}")
        skia_url=$(source $this_dir/laf/misc/skia-url.sh | xargs)
        skia_file=$(basename $skia_url)
        curl --ssl-revoke-best-effort -L -o "$skia_file" "$skia_url"
        unzip "$skia_file" -d skia
    - uses: aseprite/get-ninja@main
    - uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: x64
    - name: Generating Makefiles
      shell: bash
      run: |
        export enable_ccache=off
        export laf_backend=skia

        if [[ "${{ matrix.scripting }}" == "lua" ]] ; then
          export enable_scripting=on
        else
          export enable_scripting=off
        fi

        export skia_arch=x64

        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DENABLE_CCACHE=$enable_ccache \
          -DLAF_BACKEND=$laf_backend \
          -DSKIA_DIR=$(realpath skia) \
          -DSKIA_LIBRARY_DIR=$(realpath skia/out/Release-$skia_arch)
    - name: Compiling
      shell: bash
      run: |
        cd build && ninja
        echo LLLLLSSSSS
        ls ..
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: test-build2
        path: build/bin/**
